spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5433/microservices
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
jwt:
  secret: "randomPhrase"
  header: "Authorization"
  expiration: "1800000"